// Code generated by goyacc -o querystring.y.go querystring.y. DO NOT EDIT.

//line querystring.y:2
package querystring

import __yyfmt__ "fmt"

//line querystring.y:2

import (
	"github.com/MichealJl/querystring/condition"
)

//line querystring.y:9
type yySymType struct {
	yys int
	s   string
	n   int
	q   condition.Condition
}

const tNOT = 57346
const tOR = 57347
const tAND = 57348
const tSTRING = 57349
const tPHRASE = 57350
const tNUMBER = 57351
const tTO = 57352
const tCOLON = 57353
const tLEFTBRACKET = 57354
const tRIGHTBRACKET = 57355
const tLEFTRANGE = 57356
const tRIGHTRANGE = 57357

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"tNOT",
	"tOR",
	"tAND",
	"tSTRING",
	"tPHRASE",
	"tNUMBER",
	"tTO",
	"tCOLON",
	"tLEFTBRACKET",
	"tRIGHTBRACKET",
	"tLEFTRANGE",
	"tRIGHTRANGE",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 55

var yyAct = [...]int8{
	3, 42, 36, 32, 41, 39, 14, 35, 31, 13,
	12, 11, 19, 20, 21, 38, 40, 6, 30, 17,
	8, 9, 10, 16, 26, 5, 13, 12, 11, 23,
	27, 25, 29, 28, 18, 22, 8, 9, 10, 33,
	37, 34, 13, 12, 11, 12, 11, 4, 11, 1,
	2, 24, 7, 0, 15,
}

var yyPact = [...]int16{
	13, -1000, -1000, 38, -1000, 13, 29, -1000, 12, 26,
	-1000, 13, 13, 13, 22, -1000, 17, -1000, -1000, -1000,
	42, 40, -1000, 13, -1000, 23, 5, -7, 32, -8,
	-1000, -1000, 33, 0, -10, -1000, 7, -11, -1000, -1000,
	-14, -1000, -1000,
}

var yyPgo = [...]int8{
	0, 52, 51, 47, 0, 50, 49,
}

var yyR1 = [...]int8{
	0, 6, 5, 4, 4, 4, 4, 4, 4, 3,
	3, 3, 2, 2, 2, 2, 2, 2, 1, 1,
	1, 1, 1,
}

var yyR2 = [...]int8{
	0, 1, 1, 1, 3, 3, 3, 2, 3, 1,
	5, 3, 3, 4, 5, 3, 4, 5, 1, 2,
	1, 2, 1,
}

var yyChk = [...]int16{
	-1000, -6, -5, -4, -3, 12, 4, -1, 7, 8,
	9, 6, 5, 4, -4, -3, 11, 7, 8, -4,
	-4, -4, 13, 12, -2, 14, -4, 7, 10, 9,
	13, 15, 10, 7, 9, 15, 10, 7, 15, 15,
	9, 15, 15,
}

var yyDef = [...]int8{
	0, -2, 1, 2, 3, 0, 0, 9, 18, 20,
	22, 0, 0, 0, 0, 7, 0, 19, 21, 5,
	6, 8, 4, 0, 11, 0, 0, 0, 0, 0,
	10, 12, 0, 0, 0, 15, 0, 0, 13, 16,
	0, 14, 17,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line querystring.y:31
		{
			yylex.(*lexerWrapper).query = yyDollar[1].q
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line querystring.y:37
		{
			yyVAL.q = yyDollar[1].q
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line querystring.y:43
		{
			yyVAL.q = yyDollar[1].q
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line querystring.y:47
		{
			yyVAL.q = yyDollar[2].q
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
//line querystring.y:51
		{
			yyVAL.q = condition.NewAndCondition(yyDollar[1].q, yyDollar[3].q)
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line querystring.y:55
		{
			yyVAL.q = condition.NewOrCondition(yyDollar[1].q, yyDollar[3].q)
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
//line querystring.y:59
		{
			yyVAL.q = condition.NewNotCondition(nil, yyDollar[2].q)
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
//line querystring.y:63
		{
			yyVAL.q = condition.NewNotCondition(yyDollar[1].q, yyDollar[3].q)
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line querystring.y:68
		{
			yyVAL.q = yyDollar[1].q
		}
	case 10:
		yyDollar = yyS[yypt-5 : yypt+1]
//line querystring.y:72
		{
			q := yyDollar[4].q
			q.SetField(yyDollar[1].s)
			yyVAL.q = q
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line querystring.y:78
		{
			q := yyDollar[3].q
			q.SetField(yyDollar[1].s)
			yyVAL.q = q
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line querystring.y:86
		{
			min := yyDollar[2].s
			yyVAL.q = condition.NewRangeCondition(&min, nil)
		}
	case 13:
		yyDollar = yyS[yypt-4 : yypt+1]
//line querystring.y:91
		{
			max := yyDollar[3].s
			yyVAL.q = condition.NewRangeCondition(nil, &max)
		}
	case 14:
		yyDollar = yyS[yypt-5 : yypt+1]
//line querystring.y:96
		{
			min := yyDollar[2].s
			max := yyDollar[4].s
			yyVAL.q = condition.NewRangeCondition(&min, &max)
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line querystring.y:101
		{
			min := yyDollar[2].s
			yyVAL.q = condition.NewRangeCondition(&min, nil)
		}
	case 16:
		yyDollar = yyS[yypt-4 : yypt+1]
//line querystring.y:106
		{
			max := yyDollar[3].s
			yyVAL.q = condition.NewRangeCondition(nil, &max)
		}
	case 17:
		yyDollar = yyS[yypt-5 : yypt+1]
//line querystring.y:111
		{
			min := yyDollar[2].s
			max := yyDollar[4].s
			yyVAL.q = condition.NewRangeCondition(&min, &max)
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line querystring.y:119
		{
			yyVAL.q = condition.NewStringCondition(yyDollar[1].s)
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line querystring.y:123
		{
			yyVAL.q = condition.NewOrCondition(condition.NewStringCondition(yyDollar[1].s), condition.NewStringCondition(yyDollar[2].s))
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line querystring.y:127
		{
			yyVAL.q = condition.NewPhraseCondition(yyDollar[1].s)
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
//line querystring.y:131
		{
			yyVAL.q = condition.NewOrCondition(condition.NewPhraseCondition(yyDollar[1].s), condition.NewPhraseCondition(yyDollar[2].s))
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line querystring.y:135
		{
			yyVAL.q = condition.NewNumberCondition(yyDollar[1].s)
		}
	}
	goto yystack /* stack new state and value */
}
